### ISSUE TITLE
IDLV 1.1.2 asks for libhtd.so.0

### ISSUE THREAD

**Issue by faseehahmad** [DeMaCS-UNICAL/I-DLV#1]
I tried to  run idlv_1.1.2_linux_x86-64_supporting-python2-sparql-sql after making an executable. But it gives the following error

./idlv_1.1.2_linux_x86-64_supporting-python2-sparql-sql: error while loading shared libraries: libhtd.so.0: cannot open shared object file: No such file or directory

Are the source libraries missing? These libraries are present in stand alone version of 1.1.1. 
Thank you

**Comment by jessicazangari** [comment]
Dear faseehahmad,

in order to use I-DLV 1.1.2 supporting python, you need to install the following libraries:

  1. the libraries **unixodbc**, **libodbc1**, **librdf0-dev**;
  2. the library **python3.5-dev** (if you are using Python3) or **python2.7-dev** (if you are using Python2).
  3. the library **htd 1.2.0** available [here](https://github.com/mabseher/htd/releases/tag/1.2).

In addition, in order to use the SPARQL remote directives the following Python modules are required: 
  1. **rdflib**;
  2. **SPARQLWrapper**.

Please notice that the available executable of I-DLV 1.1.1 does not support support python functionalities.

However, we just released I-DLV v1.1.3 with standalone versions supporting python features. In this case you just need to install:
  1. **Python3.5** (if you are using Python3) or **Python2.7** (if you are using Python2).

Moreover, as in case of release 1.1.2, in order to use the SPARQL remote directives the following Python modules are required: 
  1. **rdflib**;
  2. **SPARQLWrapper**.

Let us know. For further info or details, please write to i-dlv@googlegroups.com.
